import NiceModal from "@ebay/nice-modal-react";
import MemberSignTabModal from "modals/member/sign/MemberSignTabModal";
import PaymentModal from "routes/order/summary/PaymentModal";
import SideMenu from "modals/sideMenu/SideMenu";
import ShippingInfoAddModal from "modals/member/shippingInfo/ShippingInfoAddModal";
import Filter from "modals/filter/Filter";
import ReviewModal from "modals/detail/ReviewModal";
import ReviewModifyModal from "modals/detail/ReviewModifyModal";
import ConfirmModal from "modals/confirm/ConfirmModal";
import AddCartCountModal from "modals/cart/AddCartCountModal";
import SearchModal from "modals/search/SearchModal";
import QuestionModal from "modals/question/QuestionModal";
import AnswersModal from "modals/question/answer/AnswersModal";
import ShippingInfoSelectModal from "modals/member/shippingInfo/ShippingInfoSelectModal";
import ShippingInfoEditModal from "modals/member/shippingInfo/ShippingInfoEditModal";
import PaymentMethodSelectModal from "modals/member/paymentMethod/PaymentMethodSelectModal";
import TrackOrderModal from "modals/order/TrackOrderModal"
import ProductManagerModal from "modals/manager/ProductManagerModal";
import EditorPreviewModal from "modals/manager/EditorPreviewModal";
import DisputeModal from "modals/dispute/DisputeModal";
import NextDisputeModal from "modals/dispute/NextDisputeModal";
import AccountVerificationModal from "modals/accountVerification/AccountVerificationModal";
import NextVerificationModal from "modals/accountVerification/NextVerificationModal";
import AccountDisabledModal from "modals/accountDisabled/AccountDisabledModal";
import MemberSignInModal from "modals/member/sign/signIn/MemberSignInModal";
import PurchaseOrderModal from "modals/order/PurchaseOrderModal";
import AddressModal from "modals/address/AddressModal";
import AddressCityModal from "modals/address/AddressCityModal";
import LoginHistoryModal from "modals/loginHistory/LoginHistoryModal";
import WarningModal from "modals/warning/WarningModal";
import ShippingInfoDetailModal from "modals/shippingInfo/ShippingInfoDetailModal";
import ShippingInfoUpdateModal from "modals/shippingInfo/update/ShippingInfoUpdateModal";
import AllCartsInfoDetailModal from "modals/cart/admin/AllCartsInfoDetailModal";
import ChatModal from "modals/chat/ChatModal";
import CategoryRegisterModal from "modals/category/CategoryRegisterModal";
import AddProductOptionModal from "modals/product/AddProductOptionModal";
import MemoModal from "modals/memo/MemoModal";
import PurchaseOrderShippingInfoEditModal from "modals/order/PurchaseOrderShippingInfoEditModal";
import BrandRegisterModal from "modals/category/BrandRegisterModal";
import AdminPurchaseOrderModal from "modals/order/AdminPurchaseOrderModal";
import AddressKrModal from "modals/address/kr/AddressKrModal";
import VendorRegModal from "modals/manager/VendorRegModal";
import VendorSelectModal from "modals/manager/VendorSelectModal";
import ReturnCancelConfirmModal from "modals/confirm/ReturnCancelConfirmModal";
import CheckSelectModal from "modals/manager/CheckSelectModal";
import ProductStatusModal from "modals/product/ProductStatusModal";
import ExhibitionDetailModal from "modals/exhibition/ExhibitionDetailModal";
import PromotionDetailModal from "modals/promotion/PromotionDetailModal";
import CheckSelectProductModal from "modals/manager/CheckSelectProductModal";
import SelectedProductModal from "modals/product/SelectedProductModal";
import ShippingInfoAddKrModal from "modals/member/shippingInfo/ShippingInfoAddKrModal";

function ModalHandler() {
    NiceModal.register("memberSignTabModal", MemberSignTabModal);
    NiceModal.register("memberSignIn", MemberSignInModal);
    NiceModal.register("paymentModal", PaymentModal);
    NiceModal.register("sideMenu", SideMenu);
    NiceModal.register("shippingInfoAddModal", ShippingInfoAddModal);
    NiceModal.register("shippingInfoAddKrModal", ShippingInfoAddKrModal);
    NiceModal.register("shippingInfoSelectModal", ShippingInfoSelectModal);
    NiceModal.register("shippingInfoEditModal", ShippingInfoEditModal);
    NiceModal.register("purchaseOrderShippingInfoEditModal", PurchaseOrderShippingInfoEditModal);
    NiceModal.register("filter", Filter);
    NiceModal.register("review", ReviewModal);
    NiceModal.register("reviewModify", ReviewModifyModal);
    NiceModal.register("confirm", ConfirmModal);
    NiceModal.register("returnCancelConfirm", ReturnCancelConfirmModal);
    NiceModal.register("addCartCount", AddCartCountModal);
    NiceModal.register("search", SearchModal);
    NiceModal.register("questions", QuestionModal);
    NiceModal.register("answers", AnswersModal);
    NiceModal.register("paymentMethodSelectModal", PaymentMethodSelectModal);
    NiceModal.register("trackOrder", TrackOrderModal);
    NiceModal.register("purchaseOrder", PurchaseOrderModal);
    NiceModal.register("adminPurchaseOrder", AdminPurchaseOrderModal);
    NiceModal.register("productManagerModal", ProductManagerModal);
    NiceModal.register("editorPreviewModal", EditorPreviewModal);
    NiceModal.register("dispute", DisputeModal);
    NiceModal.register("nextDispute", NextDisputeModal);
    NiceModal.register("accountVerification", AccountVerificationModal);
    NiceModal.register("nextVerification", NextVerificationModal);
    NiceModal.register("accountDisabled", AccountDisabledModal);
    NiceModal.register("address", AddressModal);
    NiceModal.register("addressCity", AddressCityModal);
    NiceModal.register("loginHistory", LoginHistoryModal);
    NiceModal.register("warning", WarningModal);
    NiceModal.register("shippingInfoDetail", ShippingInfoDetailModal);
    NiceModal.register("shippingInfoUpdate", ShippingInfoUpdateModal);
    NiceModal.register("allCartsInfoDetail", AllCartsInfoDetailModal);
    NiceModal.register("chat", ChatModal);
    NiceModal.register("categoryRegister", CategoryRegisterModal);
    NiceModal.register("brandRegister", BrandRegisterModal);
    NiceModal.register("productOption", AddProductOptionModal);
    NiceModal.register("memo", MemoModal);
    NiceModal.register("addressKr", AddressKrModal);
    NiceModal.register("vendorReg", VendorRegModal);
    NiceModal.register("checkSelect", CheckSelectModal);
    NiceModal.register("checkSelectProduct", CheckSelectProductModal);
    NiceModal.register("productStatus", ProductStatusModal);
    NiceModal.register("exhibitionDetail", ExhibitionDetailModal);
    NiceModal.register("promotionDetail", PromotionDetailModal);
    NiceModal.register("selectedProduct", SelectedProductModal);
}

export default ModalHandler;